---
title: "Test simulateur"
output: cleanrmd::html_document_clean
runtime: shiny_prerendered    
---

# Lien social

```{r context="render", echo=FALSE}
library(shiny)
numericInput(
      inputId = 'nb_habitants',    # Identifiant unique
      label = "Nombre d'habitants", # Texte du champ
      value = 5000,               # Valeur par défaut
      step = 50)
numericInput(
      inputId = 'temps_discu',    # Identifiant unique
      label = "Temps passé à discuter en heure(s)", # Texte du champ
      value = 0.5,               # Valeur par défaut
      step = 0.1
    )
numericInput(
      inputId = 'part_actifs',    # Identifiant unique
      label = "Part des commerçants très actifs en %", # Texte du champ
      value = 0.2,               # Valeur par défaut
      min = 0,
      max = 1,
      step = 0.1)
numericInput(
      inputId = 'smic_horaire',    # Identifiant unique
      label = "SMIC horaire en €", # Texte du champ
      value = 60               # Valeur par défaut
      )
```

## Résultat

```{r context = "server", echo=FALSE}
output$nb_habitants <- renderText({
  paste(input$nb_habitants, "habitants")
})
output$temps_discu <- renderText({
  paste(input$temps_discu, "heure(s) passée(s) à discuter (soit", input$temps_discu*60, "minutes)")
})
output$part_actifs <- renderText({
  paste(input$part_actifs*100, "% de commerçants actifs")
})
output$smic_horaire <- renderText({
  paste(input$smic_horaire, "de SMIC horaire en €")
})
output$resultat <- renderText({
  paste(input$nb_habitants * input$temps_discu * input$part_actifs * input$smic_horaire, "€")
})
resultat <- renderText({
  paste(input$nb_habitants * input$temps_discu * input$part_actifs * input$smic_horaire, "€")
})
```

Pour : 

- `r textOutput("nb_habitants")` 
- `r textOutput("temps_discu")` 
- `r textOutput("part_actifs")` 
- `r textOutput("smic_horaire")` 
- test 2 : `r resultat` 

**La valeur monétaire basée sur la formulé _Nombre d'habitants * Temps de discussion * Part de commerçants actifs * SMIC horaire_ est donc :**

<FONT COLOR="red">

`r textOutput("resultat")` 

</FONT>

